# Generated by Django 4.2.5 on 2023-10-01 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=65)),
                ('lastName', models.CharField(max_length=65)),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('emailAddress', models.EmailField(max_length=254)),
                ('phoneNumber', models.CharField(max_length=10)),
                ('countryCode', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('transactionId', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('timestamp', models.DateField(auto_now=True)),
                ('amountInUSD', models.FloatField()),
                ('amountInIRR', models.FloatField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
        ),
    ]
